### ISSUE TITLE
Mobiele devices detecteren

### ISSUE THREAD

**Issue by toonvandeputte** [MakeInBelgium/babbelbox#14]
Op mobiele devices is de flow anders dan op desktop. Het belangrijkste is hier dat de app eerst geïnstalleerd wordt door de gebruiker.

In de functie 'browserDetect' of evt in een nieuwe functie zou dus moeten gedetecteerd worden of het om een mobiele user gaat, en op basis hiervan een alert toegevoegd.

**Comment by vdwijngaert** [comment]
Ik neem deze wel even op.
