### ISSUE TITLE
min/max aantal tekens voor in te vullen waarden

### ISSUE THREAD

**Issue by toonvandeputte** [MakeInBelgium/babbelbox#16]
Om te vermijden dat urls te lang worden, of dat er duplicate kanaalnamen zijn, best een sensible min/max length op de tekstvelden invoeren en feedback geven tijdens input.

**Comment by spijs** [comment]
#29 zou dit moeten oplossen. Momenteel als sensible default: naam+locatie < 200 chars. Foutboodschap toont wel maximaal 100.

**Comment by vdwijngaert** [comment]
Lijkt te werken!
