### ISSUE TITLE
Instructies toevoegen om paswoord in te stellen

### ISSUE THREAD

**Issue by allora-pieter** [MakeInBelgium/babbelbox#18]
Uit de feedback van de Woon Zorg Centra kwam onmiddellijk de vraag naar de veiligheid.

Oplossing: in de tekst bovenaan de instructie geven om je praatbox te beveiligen met een paswoord.

5. De praatbox start op!
->
5. De praatbox start op! Onthou om straks op het ronde icoontje met de letter i te klikken, en een password toe te voegen, dan pas is je praatbox veilig!

**Comment by nobels** [comment]
staat er al bij

**Comment by allora-pieter** [comment]
safari <img width="107" alt="Screenshot 2020-03-16 at 19 59 07" src="https://user-images.githubusercontent.com/60920457/76791327-eaddaf00-67c0-11ea-82ca-1a905707a48a.png">
chrome
<img width="252" alt="Screenshot 2020-03-16 at 19 59 02" src="https://user-images.githubusercontent.com/60920457/76791336-f03af980-67c0-11ea-8680-d05feb7d12a5.png">
