### ISSUE TITLE
Gebruiksvriendelijkheid en toegankelijkheid check-up

### ISSUE THREAD

**Issue by vdwijngaert** [MakeInBelgium/babbelbox#20]
Next up; zien dat zoveel mogelijk mensen er intuïtief mee aan de slag kunnen. Kan er iemand in het kader daarvan eens naar de ux en a11y kijken? 

Out the top of my head zie ik bv:

- [ ] De uitleg is wat veel tekst, en duwt het formulier naar beneden
- [ ] De tekst is mogelijk te klein voor senioren
- [ ] Beter `<label>` gebruiken voor de labels ipv wat er nu is (plays nicer on mobile + schermlezers etc)
- [ ] Form kan niet met enter worden verzonden

**Uiteraard:** Dit is mijn mening. Feel free to discuss.

**Comment by allora-pieter** [comment]
Niet akkoord met je 1e opmerking dat de uitleg te veel tekst is. Veel niet technische mensen, en oudere mensen, hebben deze houvast en uitleg nodig.

**Comment by vdwijngaert** [comment]
Je begrijpt me verkeerd, ik zeg niet dat er te veel uitleg is. Ik heb het enkel over de formattering en de plaats waar de tekst staat. Nu wordt het formulier naar onderen geduwd, en is het al wat veel tekst om in één oogopslag te vatten. 

Een mogelijke oplossing daarvoor is de uitleg/stappenplan inkorten (en eventueel wat visueler maken), en een knop voorzien die meer uitleg opent in een pop-up/modal.

**Comment by toonvandeputte** [comment]
Dat het form naar onder geduwd wordt, is imho niet echt een probleem, omdat we echt wel graag hebben dat ze eerst de tekst lezen en niet zomaar beginnen invullen. Mss moet 'ie wel collapsible zijn (en dat onthouden in een cookie of zo?)

**Comment by toonvandeputte** [comment]
Dat van die missing label elementen had ik ook al gezien, maar is blijkbaar een Bootstrap ding. Als ik die toevoegde, brak de layout. Maar is wss wel op te lossen.

**Comment by toonvandeputte** [comment]
Issues opgesplitst in #25 #26 #27
