### ISSUE TITLE
Niet-compatibel met Brave

### ISSUE THREAD

**Issue by koenHuybrechts** [MakeInBelgium/babbelbox#21]
In [Brave](https://brave.com/) worden bepaalde trackers automagisch geblokkeerd, zoals de Google Tag Manager.

Foutmelding:
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

**Comment by vdwijngaert** [comment]
En dat breekt de uitvoering van de rest van de JS? Nog steeds?

**Comment by vdwijngaert** [comment]
Is niet GTM, is een probleem met Jitsi. Maar in Brave kom je waarschijnlijk nog wel dergelijke dingen tegen. Volgens mij kan je dit ook gewoon oplossen door dit uit te vinken:

![image](https://user-images.githubusercontent.com/772137/76810344-07441080-67ee-11ea-8678-69e18d3cadfa.png)

Error:

> [modules/util/JitsiLocalStorage.js] <new <anonymous>>:  DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

**Comment by vdwijngaert** [comment]
Alleszins niets waar wij iets aan kunnen doen. Eventueel bij jitsi zelf eens horen?
