### ISSUE TITLE
cachebusting static assets

### ISSUE THREAD

**Issue by toonvandeputte** [MakeInBelgium/babbelbox#22]
js en css files moeten voorzien worden van een versie-queryparam zodat oude versies uit cache niet gebruikt worden

**Comment by vdwijngaert** [comment]
Gezien het momenteel gewoon allemaal statische bestanden zijn én we geen dev workflow hebben, misschien starten met manueel een versienummer toe te voegen aan de links naar de script files?

```html
  <link href="./assets/style.css" rel="stylesheet">
```

Wordt dan:

```html
  <link href="./assets/style.css?v2020.03.16.x" rel="stylesheet">
```

Of, gezien er volk bezig is met deployment naar azure; kunnen we on deploy een replace doen op een string `{VER}` ofzo, wat dan bijvoorbeeld wordt vervangen door de (short) commit hash?

@nobels @BerendWouters

**Comment by vdwijngaert** [comment]
Zie voor een voorbeeld naar https://github.com/MakeInBelgium/babbelbox/pull/36 eventueel?

@BerendWouters kan iets soortgelijk met azure?

**Comment by toonvandeputte** [comment]
Was dit nu al resolved via een ander issue?

**Comment by vdwijngaert** [comment]
Als deployment nog steeds op mijn vps is, wel ja (zie {VERSION} placeholder)
