### ISSUE TITLE
Instructies compacter/scanbaarder

### ISSUE THREAD

**Issue by toonvandeputte** [MakeInBelgium/babbelbox#27]
De uitleg is wat veel tekst, en duwt het formulier naar beneden. Tekst beter scanbaar/collapsible maken. Evt link naar pagina met extra (uitgebreide) uitleg.

**Comment by pieterprovoost** [comment]
Zoals gesuggereerd op Slack: ik zou de uitleg en formuliervelden samen houden. Nu moet je nogal veel switchen tussen boven en onder om er wijs uit te raken.

<img width="600" alt="Screenshot 2020-03-16 at 22 27 48" src="https://user-images.githubusercontent.com/490041/76801254-8ed15580-67d5-11ea-8635-d6720bff937e.png">

**Comment by spijs** [comment]
Kan iets meer in deze richting, of echt links -> rechts zoals op drawing hierboven?
![image](https://user-images.githubusercontent.com/2649984/76804004-7ebc7480-67db-11ea-957a-2a5f19657a9e.png)
_disclaimer: quick and dirty om gewoon te begrijpen waar we naar toe willen :)_

**Comment by toonvandeputte** [comment]
Ik zou precies voor kolommen gaan (veld links, uitleg rechts) die dan onder elkaar komen bij smallere schermen.

**Comment by toonvandeputte** [comment]
@nobels heeft een collapsible uitleg geïntegreerd. May need some tweaks, maar voldoet voorlopig.
