### ISSUE TITLE
FAQ-pagina toevoegen

### ISSUE THREAD

**Issue by koenHuybrechts** [MakeInBelgium/babbelbox#30]
Er zijn wel enkele vragen die beantwoord zullen moeten worden.
Deze zijn al opgelijst in een document. 10 vragen en hun antwoorden.
Zie: https://docs.google.com/presentation/d/1UzhwKhPo_CY9kIW727_CnjXgZJkMBVx88KJvqBDf8y0/edit#slide=id.g7f216d806c_19_0

Het zou goed zijn als deze in de tool beschikbaar komen.

Persoonlijk zou ik gaan voor een aparte pagina (nieuw tabblad). Geen download van PDF en niet linken naar de presentatie.

**Comment by allora-pieter** [comment]
Agree, aparte pagina, nieuw tabblad, dat kan dan openstaan als ze problemen hebben.

Check zeker de oude urls die er nog in staan.

**Comment by allora-pieter** [comment]
oude urls in google docs aangepast, 
sectie met veelgestelde vragen is ok en mag op de website komen.
