### ISSUE TITLE
spaties in velden breekt de link

### ISSUE THREAD

**Issue by Jonathan-Moreel** [MakeInBelgium/babbelbox#35]
[disclaimer, ik ben geen programmeur]
Wanneer in de naam van de kamer of de locatie een spatie wordt getypt, dan werkt de link niet wanneer deze via bijv facebook messenger of mail wordt verstuurd. Zie screenshot, ekel het stuk tot de eerste spatie wordt omgezet in een link
Suggestie 1: zorgen dat er geen spaties in de velden kunnen worden gezet (quickfix)
Suggestie 2: spatie in de link omzetten naar %20 (hiervoor is meer testen nodig om te zien of het overal werkt)

![Capture praatbox messenger ](https://user-images.githubusercontent.com/62265795/76801903-db696080-67d6-11ea-8de0-3d1e9943b499.JPG)

**Comment by vdwijngaert** [comment]
Hoi Jonathan!

Bedankt om te melden. Dit zou inmiddels moeten opgelost zijn door de aanpassingen vanwege #29. Op de site zelf draait momenteel nog een oude versie. :crossed_fingers: 

Closing for now!
