### ISSUE TITLE
whatsapp knop doet het niet

### ISSUE THREAD

**Issue by nobels** [MakeInBelgium/babbelbox#37]
Ik zou deze weg doen en pas visueel zetten als deze werkt.

of werkt dit enkel op telefoon ? (dan moet er een conditie zijn)

**Comment by allora-pieter** [comment]
werkt op macOS en iOS

**Comment by vdwijngaert** [comment]
Werkt hier ook overal! Was mss nog de versie zonder encodeURIComponent?
