### ISSUE TITLE
mailto link knop bovenaan (naast de bestaande knoppen)

### ISSUE THREAD

**Issue by allora-pieter** [MakeInBelgium/babbelbox#38]
een MAIL LINK knop bovenaan lijkt ons  interessant.
de senioren kunnen meestal wel mail sturen, maar copy paste is misschien wat moeilijker?

Ook op mobiel is copy/paste + switch naar mail app moeilijker
jonathan
+1 Zeker interessant voor wanneer de box wordt aangemaakt vanop smartphone/tablet

**Comment by toonvandeputte** [comment]
Resolved in 01c85d15f58c7ba36027bcd8bb706087c71d553b
