### ISSUE TITLE
Vertaalbaarheid

### ISSUE THREAD

**Issue by toonvandeputte** [MakeInBelgium/babbelbox#40]
Applicatie zou vlot te vertalen moeten zijn, met name in het Frans (maar mss ook Turks, Pools, etc).

Kan wss best door alle strings in een json file te steken, en deze afh. van taalselectie in te laden, met een eenvoudige fallback naar NL. Wss bestaan hier al standaarden voor, maar ik heb persoonlijk alleen ervaring met .po/.mo files.

Het zou daarbij ook goed zijn als niet-technische personen relatief makkelijk vertaling kunnen doen, via een spreadsheet die makkelijk om te zetten is naar json bvb.

**Comment by toonvandeputte** [comment]
Het vertalen zelf, zou ik in aparte issues steken, btw

**Comment by localdevm** [comment]
Voor localisatie stel ik volgend voor: https://crowdin.com/

Ik heb hier voor het open-contributors project ervaring mee en is zeer gemakkelijk te gebruiken, zelfs voor niet technische personen. In verband met de implementatie hiervan of localisatie in het huidige project moet ik nog bekijken.

**Comment by toonvandeputte** [comment]
Crowdin is een betalend product met een abo, daar zou ik niet graag van afhankelijk zijn.

**Comment by toonvandeputte** [comment]
.pot file aangemaakt in https://github.com/MakeInBelgium/babbelbox/commit/ac3b2813d4686d3e2dd1dbe5c649d858b041d1ef

Ik denk dat het nu vooral belangrijk is dat er iemand effectief de FR vertaling gaat maken. De implementatie zal dan wel los lopen, het gaat niet om extreem veel tekst.

**Comment by toonvandeputte** [comment]
Er zit een translation csv in _data van de Jekyll branch: https://github.com/MakeInBelgium/babbelbox/tree/jekyll/_data

**Comment by TomCools** [comment]
Damn, niet gezien dat er een Jekyll branch was. Ik heb het volledig in Javascript/HTML gemaakt. Een review is welkom, anders verplaats ik mijn engelse teksten wel naar jouw Jekyll data.

https://github.com/MakeInBelgium/babbelbox/pull/61

**Comment by TomCools** [comment]
Nieuwe Pull request met gebruik van Jekyll: https://github.com/MakeInBelgium/babbelbox/pull/63

**Comment by nobels** [comment]
Vertaling zit er in door Toon.
