### ISSUE TITLE
Versienummer automatisch verhogen bij deployment

### ISSUE THREAD

**Issue by koenHuybrechts** [MakeInBelgium/babbelbox#41]
Als we een nieuwe versie online zetten, deze ook taggen en het versienummer meenemen in de deployment pipeline.

**Comment by toonvandeputte** [comment]
Goed idee, maar hoe zou je dat precies doen? Toen ik er eergisteren ben ingevlogen, heb ik er specifiek op gelet om geen extra technische dependencies (gulp, sass, npm...) te introduceren om ervoor te zorgen dat zoveel mogelijk mensen kunnen bijdragen. Ik weet niet of dat nog altijd zo belangrijk is, maar het is een overweging.

Dus best iets dat server side gebeurt, denk ik, obv een tag die in git wordt meegegeven of zo?

**Comment by vdwijngaert** [comment]
Check :) Zie #36
